#!/bin/sh

set -e

# We'll also need to clean up links to make sure that our new start
# link is installed by update-rc.d.
force_remove_old_init_links() {
	rm -f /etc/rc?.d/[SK]*_program_
}

case "${1:-}" in
	configure)
	if [ "$2"x = "0.1"x ] ; then
		force_remove_old_init_links
	fi
	;;

	*) :;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/_program_" ]; then
	update-rc.d _program_ defaults >/dev/null || exit $?
fi
# End automatically added section

